runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: img10.app
  secure: always
  http_headers:
    Access-Control-Allow-Origin: http://localhost:7070
